### ISSUE TITLE
After saving field that's a Matrix with Meta, logged out and can't log back in

### ISSUE THREAD

**Issue by dougstjohn** [flipbox/meta#2]
2017-06-16 11:22:11 [172.28.128.1][-][er6ubvlnat5np19m4qtgpnrq63][error][craft\base\ApplicationTrait::getTargetLanguage] Tried to determine the user’s preferred language, but got this exception: Declaration of craft\behaviors\ElementQueryBehavior::events($value) should be compatible with yii\base\Behavior::events()
2017-06-16 11:22:11 [172.28.128.1][-][er6ubvlnat5np19m4qtgpnrq63][error][yii\base\ErrorException:64] yii\base\ErrorException: Cannot declare class craft\behaviors\ContentBehavior, because the name is already in use in /var/www/html/storage/runtime/compiled_classes/ContentBehavior.php:0
Stack trace:
#0 /var/www/html/vendor/craftcms/cms/src/elements/db/ElementQuery.php(49): Craft::autoload()
#1 /var/www/html/vendor/craftcms/cms/src/elements/db/ElementQuery.php(49): ::spl_autoload_call()
#2 /var/www/html/vendor/yiisoft/yii2/BaseYii.php(288): yii\BaseYii->unknown()
#3 /var/www/html/vendor/craftcms/cms/src/elements/db/UserQuery.php(30): yii\BaseYii::autoload()
#4 /var/www/html/vendor/craftcms/cms/src/elements/db/UserQuery.php(30): ::spl_autoload_call()
#5 /var/www/html/vendor/yiisoft/yii2/BaseYii.php(288): yii\BaseYii->unknown()
#6 /var/www/html/vendor/craftcms/cms/src/elements/User.php(138): yii\BaseYii::autoload()
#7 /var/www/html/vendor/craftcms/cms/src/elements/User.php(138): ::spl_autoload_call()
#8 /var/www/html/vendor/craftcms/cms/src/services/Users.php(166): craft\elements\User::find()
#9 /var/www/html/vendor/craftcms/cms/src/controllers/UsersController.php(108): craft\services\Users->getUserByUsernameOrEmail()
#10 /var/www/html/vendor/yiisoft/yii2/base/InlineAction.php(57): craft\controllers\UsersController->actionLogin()
#11 /var/www/html/vendor/yiisoft/yii2/base/InlineAction.php(57): ::call_user_func_array:{/var/www/html/vendor/yiisoft/yii2/base/InlineAction.php:57}()
#12 /var/www/html/vendor/yiisoft/yii2/base/Controller.php(156): yii\base\InlineAction->runWithParams()
#13 /var/www/html/vendor/yiisoft/yii2/base/Module.php(523): craft\controllers\UsersController->runAction()
#14 /var/www/html/vendor/craftcms/cms/src/web/Application.php(246): craft\web\Application->runAction()
#15 /var/www/html/vendor/craftcms/cms/src/web/Application.php(385): craft\web\Application->runAction()
#16 /var/www/html/vendor/craftcms/cms/src/web/Application.php(206): craft\web\Application->_processActionRequest()
#17 /var/www/html/vendor/yiisoft/yii2/base/Application.php(380): craft\web\Application->handleRequest()
#18 /var/www/html/web/index.php(21): craft\web\Application->run()
#19 {main}
2017-06-16 11:22:11 [172.28.128.1][-][er6ubvlnat5np19m4qtgpnrq63][info][application] $_GET = [
    'p' => 'admin/actions/users/login'
]

**Comment by dougstjohn** [comment]
Internal Server Errors
![screen shot 2017-06-16 at 11 59 44 am](https://user-images.githubusercontent.com/3673451/27238749-55ed72f6-528b-11e7-8587-22f0ec2f4854.png)

**Renaming Webinars and Webinar:**
An error occurred while saving this Matrix block type.

**Deleting the Webinars blocktype:**
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'meta.siteId' in 'where clause' 

**Deleting the Webinar field:**
Invalid field ID: 159

**Comment by nateiler** [comment]
@dougstjohn I haven't been able to replicate this on the latest version.  Can you?

**Comment by dougstjohn** [comment]
I haven't been able to.
